### ISSUE TITLE
Inquiry about the determination of VOCAB_SIZE and OBJ_CLASSES_SIZE in the config file

### ISSUE THREAD

**Issue by haruka0000** [davidhalladay/LayoutTransformer#6]
Hello,

I hope this message finds you well. I have been reviewing the configuration file for the project, and I noticed that the values for VOCAB_SIZE and OBJ_CLASSES_SIZE are set to 206 and 155, respectively. I would like to inquire about how these specific values were determined.

```yaml
MODEL:
    PRETRAIN: False
    ENCODER:
        NAME: 'Rel2Box'
        REL_GT: False
        VOCAB_SIZE: 206
        OBJ_CLASSES_SIZE: 155
```
I have also looked into the content of the COCO.vocab, which provides mappings between object and predicate names and their corresponding indices. Based on my understanding, for the model to predict classes accurately, OBJ_CLASSES_SIZE should be equal to either object_name_to_idx or object_idx_to_name, but it seems that 155 does not match any of these values.

```bash
key length
object_name_to_idx 177
pred_name_to_idx 7
object_pred_name_to_idx 184
object_pred_idx_to_name 184
pred_idx_to_name 7
object_idx_to_name 188
```
Could you kindly provide some insights into the rationale behind choosing the values 206 and 155 for VOCAB_SIZE and OBJ_CLASSES_SIZE? I am curious to understand the reasoning behind these numbers.

Thank you for your attention to this matter. I look forward to your response.
